### ISSUE TITLE
Problem react-native 0.68.6 ios compile

### ISSUE THREAD

**Issue by gansu18** [talsec/Free-RASP-ReactNative#11]
No work in ios with multi tarjets

Multiple commands produce '/Users/pervasive/Library/Developer/Xcode/DerivedData/ramon-guecijowjmmrnafxmvkqpjpjlotr/Build/Products/Debug-iphonesimulator/freerasp-react-native/freerasp_react_native.framework/Headers/CryptoBridgingHeader.h'

**Comment by tompsota** [comment]
Hello @gansu18,

Please try following:
1. Open your .xcworkspace file in XCode
2. Go to General > Frameworks, Libraries and Embedded Content
3. If there is Embed & Sign next to TalsecRuntime.xcframefork, change it to Do Not Embed

Let us know if that helps.


Additionally, we are very close to releasing version 2.0.0 of the FreeRASP package, which would resolve your problem with no actions needed from your side (other than importing the latest version of freeRASP). So maybe the easiest option now would be to wait for a couple of days until we release it, if you are willing to do so.

Best,
Tomas, Talsec developer

**Comment by tompsota** [comment]
Hi @gansu18  ,

We just released v3.3.1, which fixes the issue, without having to remove use_frameworks!

Best, 
Tomas, Talsec developer
