### ISSUE TITLE
How do we use this in Class based component in React Native

### ISSUE THREAD

**Issue by pradsirwt** [talsec/Free-RASP-ReactNative#14]
Thank you for this excellent library. I have a Class based component in my project. I couldn't find any example of using it in Class components in the README file. 

Could anyone point me to any guide on how to integrate in Class components?

Thanks

**Comment by tompsota** [comment]
Hello @pradsirwt,

Thanks for bringing this up.

Basically what you should do is:

- override [constructor() method](https://legacy.reactjs.org/docs/react-component.html#constructor) in the entry point to your app, where you set listeners to threats and start freeRASP by calling these two methods:
  ```
  setThreatListeners(actions);
  talsecStart(config);
  ```
  `actions` is object with your reactions to threats, [see Initialization chapter in readme](https://github.com/talsec/Free-RASP-ReactNative#initialization)
  `config` is freeRASP config object [see Configuration chapter in readme](https://github.com/talsec/Free-RASP-ReactNative#initialization)

- override [componentWillUnmount() method](https://legacy.reactjs.org/docs/react-component.html#componentwillunmount) where you clean up the listeners:
  ```
  removeThreatListeners();
  ```

Hopefully this will help. Feel free to reach us if there are any struggles with integration. 
We'll also consider adding a new example showing how to integrate freeRASP using Class components in the future. 

Best,
Tomas, Talsec developer

**Comment by msikyna** [comment]
Hello @pradsirwt ,
did the proposed solution work? We have also added it into the documentation.

Kind regards,
Talsec team

**Comment by pradsirwt** [comment]
Hi Team

No proposed did not solution work

Thanks

**Comment by tompsota** [comment]
Hello @pradsirwt,

you can take a look at a simple demo that integrates freeRASP using Class components here: https://gist.github.com/tompsota/0ae2bb6a3d49d02dd7e8ea84da4c60cf

Best,

Tomas, Talsec developer

**Comment by pradsirwt** [comment]
Thanks @tompsota 

It's working now

**Comment by gkasireddy202** [comment]
How to test the RSAP component in class component.
Can we restrict the user login into the app?
example: Disable the login button on the login page.

**Comment by DeepikaSharma5** [comment]
@tompsota I use the same coding you use. But for me the  console.log('privilegedAccess'); is not showing. How it is showing to you. @pradsirwt Can you share your working code please?
