### ISSUE TITLE
Hooks config not detected in initial render for FRIDA

### ISSUE THREAD

**Issue by pradsirwt** [talsec/Free-RASP-ReactNative#15]
**Describe the bug**
I have implemented the Free-RASP in react native as per the example, But the Frida hook is detected in the fifth re-render of Free-RASP config, so the App is open (Launch screen shown) for some time before the Restricted Page is shown from our side according to the config. 

**Expected behavior**
It should detect in the first render

**Screenshots**
![image](https://user-images.githubusercontent.com/124187171/236817432-c84d77a8-0559-44d1-8db8-8bea12aa2ebb.png)

**Please complete the following information:**
 - Device: MEMU PLAY Simulator
 - OS version:  Android - 7.1.2
 - Version of freeRASP: 2.0.1

**Comment by pradsirwt** [comment]
Hi Team,

Do we have any progress here ?

Many thanks

**Comment by tompsota** [comment]
Hello @pradsirwt,

Apologies for the delay in addressing this. We've been quite busy recently with releasing major updates for our other modules. We'll get to this shortly.

Thank you for your patience.

Tomas, Talsec developer

**Comment by pradsirwt** [comment]
Hi Team,

Do we have any progress here ?

Many thanks

**Comment by tompsota** [comment]
Hi @pradsirwt,

We did take a look at our freeRASP SDK and did not spot anything unusual. The reason for delayed detection is that some checks are more computationally expensive than others. In the freeRASP, all checks are running in the background threat. This is one of the limitations of freeRASP that will probably persist in the future.
In our BusinessRASP+ solution, each customer has the option to prioritize checks, making some subgroups critical and blocking. Unfortunately, this feature is not included in our freeRASP, where the library is not customized for every customer.
We can try to optimize each subgroup of checks (so the reaction is triggered a little bit sooner), but this will probably not solve your problem as it will always take some time to perform all the checks.

Best regards,
Talsec team
