### ISSUE TITLE
Downgrading API level

### ISSUE THREAD

**Issue by MamoshiSE** [talsec/Free-RASP-ReactNative#24]
Hey,
I was wondering if it's possible to use the library without having to use (API level 23) since my projects currently run on 21 and I am trying to avoid having to upgrade them.

Can I somehow use freeRASP 2.0.3 instead of 3+?

**Comment by tompsota** [comment]
Hello @MamoshiSE,

sure, you can install version 2.0.3 of the library with this command: `npm install freerasp-react-native@2.0.3`. 

Regards,

Tomas, Talsec developer

**Comment by msikyna** [comment]
Hello @MamoshiSE 
however, the new versions of freeRASP will come with minimal supported Android version 6.0 (API 23). We needed to increase the support version for removing the Bouncy Castle dependency.

Kind regards,
Talsec team
