### ISSUE TITLE
Getting "unofficialStore" check failed after publish on play store internal testing.

### ISSUE THREAD

**Issue by Subhendu-io** [talsec/Free-RASP-ReactNative#25]
Steps I followed.

1. Added configuration :

const raspConfig = {
    androidConfig: {
        packageName: BUNDLE_ID,
        certificateHashes: [ SIGN_CERTIFICATE_HASH ],
    },
    iosConfig: {
        appBundleId: BUNDLE_ID,
        appTeamId: TEAM_ID,
    },
    watcherMail: WATCHER_MAIL,
    isProd: true,
}

2. Added hook 
     useFreeRasp(raspConfig, actions)

3. Checking on use effect.
  appChecks.forEach((item: any) => {
      if (item.status === 'nok') {
      
         Getting ====>  Unofficial Store ( NOK );
         
      }
   });
 
 Everything else works fine.
 
 Thanks.

**Comment by xprikryl2** [comment]
Hello,

could you please send us some information about your application (watcher mail or package name) so we can look into the audit reports(logs) and investigate this issue? Please, send it to [support@talsec.app](support@talsec.app) together with a link to this issue.

Best regards,
Talsec Team

**Comment by Subhendu-io** [comment]
Hello @xprikryl2 
I mailed the details of our application. also wanted to share that.
We are only getting this error in android which env has " 2 App signing key certificates " in google play console
1. Latest
2. Legacy

Thanks.

**Comment by yardexx** [comment]
Closed due to inactivity.

If issue still persists don't hesitate to reopen it and/or contact us via mail: support@talsec.app
