### ISSUE TITLE
Increase in Build Size

### ISSUE THREAD

**Issue by shubham-imoney** [talsec/Free-RASP-ReactNative#30]
**Is your feature request related to a problem? Please describe.**
After installing the library, the release apk size increases by three times, from 56 MB to 150 MB. Is this expected? I intend to use only the jailbreak and ssl pinning features.

**Comment by shubham-imoney** [comment]
Hi @tompsota. 

Thanks for the information. Appreciate it. The minSdkVersion was indeed the reason for the increase in apk size! I'll look into either setting extractNativeLibs to true or using aab format. 

Is the privilegedAccess reaction in the library part of the open source code or binary? I have not been able to find the code for it in the repo.

**Comment by xprikryl2** [comment]
Hi @shubham-imoney,

freeRASP for React Native is just a wrapper/layer on top of the native Android and iOS libraries. The freeRASP native libraries (Android, iOS) are licensed as freemium, and their code is not available. This repository contains the code of the wrapper for React Native (native Android and iOS libraries are included as dependencies) and a sample application demonstrating the integration/usage of freeRASP. 

If you want to implement a reaction for privilegedAccess in JS, just add your custom code inside the following block as shown in the documentation:
```
privilegedAccess: () => {
    console.log('privilegedAccess');
  },
```
In our example application, if the reaction is triggered, we just modify the UI as show [here](https://github.com/talsec/Free-RASP-ReactNative/blob/master/example/src/App.tsx).

Best regards,
Ondřej, Talsec developer
