### ISSUE TITLE
Not Working on Android after upgrading react native

### ISSUE THREAD

**Issue by shubham-imoney** [talsec/Free-RASP-ReactNative#36]
**Describe the bug**
I'm unable to start my application in Android after updating react native to 0.71.14

**To Reproduce**
Update react native to 0.71.14 and run the application with free-rasp installed

**Expected behavior**
Application should work with free-rasp installed

**Screenshots**
None.

**Please complete the following information:**
 - Device: Android Redmi Note 10
 - OS version: 10
 - Version of freeRASP: ^3.4.0

**Additional context**
The error message that I'm getting when running yarn android is
`Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.aheaditec.talsec.security:TalsecSecurity-Community-ReactNative:8.3.0.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/8.3.0/TalsecSecurity-Community-ReactNative-8.3.0.pom
       - https://repo.maven.apache.org/maven2/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/8.3.0/TalsecSecurity-Community-ReactNative-8.3.0.pom
       - file:/Users/imoneynew/Desktop/code/mobile-apps/frontend/mobile/merchant/node_modules/jsc-android/dist/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/8.3.0/TalsecSecurity-Community-ReactNative-8.3.0.pom
       - https://dl.google.com/dl/android/maven2/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/8.3.0/TalsecSecurity-Community-ReactNative-8.3.0.pom
       - https://www.jitpack.io/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/8.3.0/TalsecSecurity-Community-ReactNative-8.3.0.pom
     Required by:
         project :app > project :freerasp-react-native`

**Comment by msikyna** [comment]
Hello @shubham-imoney ,
thank you for reporting the issue, @tompsota will have a look at it.

Kind regards,
Talsec team

**Comment by tompsota** [comment]
Hi @shubham-imoney,

update of RN probably made some changes in your top-level `build.gradle`, so now it does not include additions from the freeRASP's build.gradle. Probably the easiest fix is to uninstall freerasp package and install it again:

1. `yarn remove freerasp-react-native`
2. `yarn add freerasp-react-native`

Let us know if this helps.

Cheers,
Tomas, Talsec dev

**Comment by msikyna** [comment]
Hello @shubham-imoney ,

did the @tompsota answer help? 

Kind regards,
Talsec team

**Comment by shubham-imoney** [comment]
Hi @msikyna 

Apologies for the delay in replying. I haven't had the time the re-try installing the lib. I'll probably do it the coming weeks. You can go ahead and close this issue if required. I'll re-open it if needed

Thanks
