### ISSUE TITLE
Unofficial store event triggered for Firebase App Distribution

### ISSUE THREAD

**Issue by klazbaba** [talsec/Free-RASP-ReactNative#37]
**Describe the bug**
In my setup, I added `supportedAlternativeStores: ['dev.firebase.appdistribution']`. But on running the app, the unofficialStore event was triggered.

**To Reproduce**
- On set up, add `supportedAlternativeStores: ['dev.firebase.appdistribution']` in androidConfig.

**Expected behavior**
Installing the app from Firebase App tester should not trigger unofficialStore event.

**Please complete the following information:**
 - Device: TECNO CC7
 - OS version: ANDROID 9
 - Version of freeRASP: 3.4.0

**Comment by msikyna** [comment]
Hello @klazbaba ,
could you send us your watcherMail and package name on support@talsec.app? We can look at the data to see what is the source of installation.

Kind regards,
Talsec team

**Comment by msikyna** [comment]
Hello @klazbaba ,

could you elaborate further on the issue? Thank you!

Kind regards,
Talsec team

**Comment by klazbaba** [comment]
> Hello @klazbaba ,
> 
> could you elaborate further on the issue? Thank you!
> 
> Kind regards, Talsec team

The issue was that I wanted the unsupported source event to not trigger when the app is installed from firebase distribution. So I added `supportedAlternativeStores: ['dev.firebase.appdistribution']` like it was mentioned in the doc. But after installing the app via firebase distribution, the event still got triggered.

**Comment by msikyna** [comment]
Hello @klazbaba ,
please elaborate further on sending the watcherMail and package name at support@talsec.app as asked above, so we can look at the logs.

Kind regards,
Talsec team

**Comment by klazbaba** [comment]
> Hello @klazbaba , please elaborate further on sending the watcherMail and package name at [support@talsec.app](mailto:support@talsec.app) as asked above, so we can look at the logs.
> 
> Kind regards, Talsec team

We removed the check for alternate stores after I opened this issue. So I think I'll just close this.

**Comment by mthahzan** [comment]
@msikyna I am facing the same issue as the OP and I have sent the app details to the support email. Hoping we can get to the bottom of this issue.

**Comment by deepanshuisky** [comment]
Anyone solved the issue i am also facing the same.
