### ISSUE TITLE
Issue on IOS event detection

### ISSUE THREAD

**Issue by Kiran0791** [talsec/Free-RASP-ReactNative#50]
After the app is installed for the first time the event are triggered. But if the close and restarted the app its not detecting the threat.

Can i get some help on this or is there any config am missing

**Comment by msikyna** [comment]
Hello @Kiran0791 ,
could you please explain what exact threat are you referring to? Or is it all threats?

Kind regards,
Talsec team

**Comment by Kiran0791** [comment]
Hi,
Its on all threat looks like. on fresh install i am able to see secureHardwareNotAvailable but if i close the app and open again its not detecting

**Comment by tompsota** [comment]
Hi @Kiran0791 ,

First, thanks for opening the issue.

Couple of questions, so we can determine where the problem is: 
- Do you close the app completely,  or just put it in the background? 
- How long do you wait after you reopen the app? 
- Do you launch the app on a simulator or real device?


You can also check our implementation in the demo app in example folder.

Kind regards,
Tomas

**Comment by Kiran0791** [comment]
- Completely closed the app
- Reopened the app immediately and also waited for few mins
- On both real device and simulator faced the issue. pen-test were able to bypass by relaunching the app

I have followed the similar implementation as in demo app

**Comment by tompsota** [comment]
I tested the most recent version of freerasp but can't reproduce the problem. Do you use the useFreeRasp hook?

**Comment by Kiran0791** [comment]
Yes useFreeRasp is used. also A common component created and its loaded from App.js

Below is the code

`import {useFreeRasp} from 'freerasp-react-native';
import React, {useEffect, useState} from 'react';
import {androidChecks, commonChecks, iosChecks} from './Check';
import {Image, Platform, StyleSheet, View} from 'react-native';
import {Icons} from '../assets/Images';
import {Text} from 'native-base';
import TextParse from '../components/common/TextParse';
import {fontMedium} from '../../themes/variables/Fonts';
import {LogEvent} from '../actions/LogActions';

const WhoIsIn = props => {
  const [appChecks, setAppChecks] = useState([
    ...commonChecks,
    ...(Platform.OS === 'ios' ? iosChecks : androidChecks),
  ]);
  const [isCompromised, setIsCompromised] = useState(false);
  const isRelease = !__DEV__ ? true : false;
  const config = {
    androidConfig: {
      packageName: 'com.test',
      certificateHashes: ['r********************************8='],
      supportedAlternativeStores: [],
    },
    iosConfig: {
      appBundleId: 'com.test',
      appTeamId: '********',
    },
    watcherMail: '****@****.com',
    isProd: isRelease,
  };

  const actions = {
    // Android & iOS
    privilegedAccess: () => {
      setAppChecks(currentState =>
        currentState.map(threat =>
          threat.name === 'Privileged Access'
            ? {...threat, status: isRelease ? 'nok' : 'ok'}
            : threat,
        ),
      );
      LogEvent('Security Threat Detected', {type: 'privilegedAccess'});
    },
    // Android & iOS
    debug: () => {
      setAppChecks(currentState =>
        currentState.map(threat =>
          threat.name === 'Debug'
            ? {...threat, status: isRelease ? 'nok' : 'ok'}
            : threat,
        ),
      );
      LogEvent('Security Threat Detected', {type: 'debug'});
    },
    // Android & iOS
    simulator: () => {
      setAppChecks(currentState =>
        currentState.map(threat =>
          threat.name === 'Simulator'
            ? {...threat, status: isRelease ? 'nok' : 'ok'}
            : threat,
        ),
      );
      LogEvent('Security Threat Detected', {type: 'simulator'});
    },
    // Android & iOS
    appIntegrity: () => {
      setAppChecks(currentState =>
        currentState.map(threat =>
          threat.name === 'App Integrity'
            ? {...threat, status: isRelease ? 'nok' : 'ok'}
            : threat,
        ),
      );
      LogEvent('Security Threat Detected', {type: 'appIntegrity'});
    },
    // Android & iOS
    unofficialStore: () => {
      setAppChecks(currentState =>
        currentState.map(threat =>
          threat.name === 'Unofficial Store'
            ? {...threat, status: isRelease ? 'nok' : 'ok'}
            : threat,
        ),
      );
      LogEvent('Security Threat Detected', {type: 'unofficialStore'});
    },
    // Android & iOS
    hooks: () => {
      setAppChecks(currentState =>
        currentState.map(threat =>
          threat.name === 'Hooks' ? {...threat, status: 'nok'} : threat,
        ),
      );
      LogEvent('Security Threat Detected', {type: 'hooks'});
    },
    // Android & iOS
    deviceBinding: () => {
      setAppChecks(currentState =>
        currentState.map(threat =>
          threat.name === 'Device Binding'
            ? {...threat, status: 'nok'}
            : threat,
        ),
      );
      LogEvent('Security Threat Detected', {type: 'deviceBinding'});
    },
    // Android & iOS
    secureHardwareNotAvailable: () => {
      setAppChecks(currentState =>
        currentState.map(threat =>
          threat.name === 'Secure Hardware Not Available'
            ? {...threat, status: isRelease ? 'nok' : 'ok'}
            : threat,
        ),
      );
      LogEvent('Security Threat Detected', {
        type: 'secureHardwareNotAvailable',
      });
    },
    // Android & iOS
    passcode: () => {
      setAppChecks(currentState =>
        currentState.map(threat =>
          threat.name === 'Passcode' ? {...threat, status: 'ok'} : threat,
        ),
      );
      LogEvent('Security Threat Detected', {type: 'passcode'});
    },
    // iOS only
    deviceID: () => {
      setAppChecks(currentState =>
        currentState.map(threat =>
          threat.name === 'Device ID' ? {...threat, status: 'ok'} : threat,
        ),
      );
      LogEvent('Security Threat Detected', {type: 'deviceID'});
    },
    // Android only
    obfuscationIssues: () => {
      setAppChecks(currentState =>
        currentState.map(threat =>
          threat.name === 'Obfuscation Issues'
            ? {...threat, status: 'nok'}
            : threat,
        ),
      );
      LogEvent('Security Threat Detected', {type: 'obfuscationIssues'});
    },
  };

  useEffect(() => {
    setIsCompromised(checkWhoIsIn());
  });

  useEffect(() => {
    setIsCompromised(checkWhoIsIn());
  }, [JSON.stringify(appChecks)]);

  const checkWhoIsIn = () => {
    const isNokAvailable = appChecks.some(element => {
      if (element.status === 'nok') {
        return true;
      }

      return false;
    });

    return isNokAvailable;
  };

  useFreeRasp(config, actions);

  if (!isCompromised) {
    return null;
  }
  return (
    <View style={[StyleSheet.absoluteFillObject, styles.container]}>
      <Image style={styles.icon} source={Icons.unauthorized} />
      <Text style={styles.heading}>Access Denied</Text>
      <TextParse style={styles.description}>
        {
          'Sorry, You cannot access this app. Contact us at ********@***.com'
        }
      </TextParse>
    </View>
  );
};

const styles = {
  container: {
    backgroundColor: '#ffffff',
    zIndex: 9999,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 50,
  },
  icon: {
    width: 80,
    height: 80,
    resizeMode: 'contain',
  },
  heading: {
    fontFamily: fontMedium,
    fontSize: 22,
    textAlign: 'center',
    color: '#292C4E',
    marginTop: 10,
  },
  description: {
    fontSize: 18,
    textAlign: 'center',
    color: '#292C4E',
    marginTop: 8,
  },
};

export default WhoIsIn;
`

**Comment by tompsota** [comment]
Hi, the integration seems fine. I used your component with slight modifications, which you can check [here](https://gist.github.com/tompsota/e0198fdb90ff69c407b70f99b9322240). Then loaded this component in the App.tsx. However I receive the callbacks even after closing and reopening the app. 

Are you testing dev or release build? If you are on simulator and use the out-of-the-box simulator without any modifications with dev build, then you will receive just secureHardwareNotAvailable check (some checks are ignored in the dev build by freerasp automatically, see docs [here](https://github.com/talsec/Free-RASP-ReactNative?tab=readme-ov-file#dev-vs-release-version)). However this check is later ignored in the code snippet provided. There should be only log visible, but UI won't change. 
In the production build, however, you should always receive all the callbacks except passcode and deviceID, which are ignored again in the code snippet.

**Comment by Kiran0791** [comment]
It happened on release build. 
Wat is advisable. To show a screen or to crash app when threat is detected. Previously i was crashing the app and once the user relauched the app these events were not getting triggered

**Comment by tompsota** [comment]
You can read more about threats and recommended actions in our wiki [here](https://github.com/talsec/Free-RASP-Community/wiki/Threat-detection).

Anyway, the bug you describe is concerning. 
Can you explain step-by-step how to reproduce the bug?

You can also reach out to us at info@talsec.app if that option suits you better.

**Comment by pushp-rathod** [comment]
I am facing the same issue in iOS.
While restart the app 3rd time it is not detecting.?
