### ISSUE TITLE
Could not find com.aheaditec.talsec.security:TalsecSecurity-Community-ReactNative:9.0.0.

### ISSUE THREAD

**Issue by bwjctan1999** [talsec/Free-RASP-ReactNative#51]
**Describe the bug**
When building android with React Native + Expo, an Exception occurs.

`Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.aheaditec.talsec.security:TalsecSecurity-Community-ReactNative:9.0.0.
     Searched in the following locations:
       - file:/project_path/node_modules/react-native/android/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/9.0.0/TalsecSecurity-Community-ReactNative-9.0.0.pom
       - file:/project_path/node_modules/jsc-android/dist/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/9.0.0/TalsecSecurity-Community-ReactNative-9.0.0.pom
       - https://dl.google.com/dl/android/maven2/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/9.0.0/TalsecSecurity-Community-ReactNative-9.0.0.pom
       - https://repo.maven.apache.org/maven2/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/9.0.0/TalsecSecurity-Community-ReactNative-9.0.0.pom
       - https://www.jitpack.io/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/9.0.0/TalsecSecurity-Community-ReactNative-9.0.0.pom
       - file:/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/9.0.0/TalsecSecurity-Community-ReactNative-9.0.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/9.0.0/TalsecSecurity-Community-ReactNative-9.0.0.pom
     Required by:
         project :app > project :freerasp-react-native`

**Comment by tompsota** [comment]
Hi @bwjctan1999 

With Expo apps, you have to add the maven dependency containing freeRASP SDK manually, like so:

1. open `android/build.gradle` (if you don't see the android folder, run `npx expo prebuild -p android` in terminal to create it)
1. add following dependency under allprojects > repositories: 
`maven{ url "https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp" }`
1. if missing, add also 
`maven { url 'https://www.jitpack.io' }`
1. run the app

We'll update the docs as well and will be looking into possibilities how to automate this process.

Cheers,
Tomas, Talsec developer
