### ISSUE TITLE
Execution failed for task ':freerasp-react-native:minifyReleaseWithR8'.

### ISSUE THREAD

**Issue by tusharsarkar** [talsec/Free-RASP-ReactNative#60]
**Bug Description**
on ```./gradlew app:assembleRelease``` I am getting following error

Execution failed for task ':freerasp-react-native:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin: /../node_modules/freerasp-react-native/android/build/tmp/kotlin-classes/release/com/freeraspreactnative/Threat.class

**RASP Version Info**
 - Version of freeRASP: 3.7.0

**React native version info**
 - "react": "18.2.0",
 - "react-native": "0.73.6",

**Comment by tompsota** [comment]
Hi @tusharsarkar,

I'll try to reproduce the bug and get back to you ASAP.

Thanks for reporting!

Tomas from Talsec

**Comment by tusharsarkar** [comment]
@tompsota any update on this issue

**Comment by tompsota** [comment]
Hi, @tusharsarkar,

I've been busy preparing new release, but hopefully tomorrow I'll take a look at this issue.

Thanks for your patience and stay tuned!

**Comment by tusharsarkar** [comment]
Hi @tompsota ,
any update on this issue? Our release blocked due to this issue.

**Comment by tompsota** [comment]
Hi @tusharsarkar,

I reproduced the problem. To resolve it, add following code on **top** of the `settings.gradle` or `settings.gradle.kts` file (inside `android/` folder):

```groovy
pluginManagement {
    buildscript {
        repositories {
            mavenCentral()
            maven {
                url = uri("https://storage.googleapis.com/r8-releases/raw")
            }
        }
        dependencies {
            classpath("com.android.tools:r8:8.2.24")
        }
    }
}
```

The issue is that RN 0.73.x uses AGP 8.1.x which does not support sealed classes. However, these are used in our project. The support is again added in AGP 8.2. By adding the code above, you specify that you want to use the use newer version of AGP.


Hopefully this resolves your problem.

Let us know if this helped.

**Comment by tusharsarkar** [comment]
Thanks @tompsota . This resolve the issue.

**Comment by asharamseervi** [comment]
Hey @tompsota, I'm using this package with Expo, as discussed previously, and requested support for Expo SDK.
While building an app, this issue still exists for me as being an ExpoSDK user.

<img width="1102" alt="Screenshot 2024-04-22 at 1 41 49 AM" src="https://github.com/talsec/Free-RASP-ReactNative/assets/5942572/8ef6b23d-6a51-43e1-b255-cdaacf7c7d66">

To debug further, I'm providing a few more details to try:
"expo": "~50.0.15",
"react-native": "0.73.6",
 "freerasp-react-native": "^3.7.1-1",
**And as suggested, I do not have an Android directory at all. 
How can I apply those settings in app.json or anywhere you recommend?**

**Comment by tompsota** [comment]
Hi @asharamseervi ,

 I'll update the config plugin for Expo. Thanks for pointing it out.
