### ISSUE TITLE
App Integrity threat not detected in iOS device || Expo React Native

### ISSUE THREAD

**Issue by Mr-harsh10** [talsec/Free-RASP-ReactNative#68]
I am working on a React Native Expo app. During penetration testing, the tester was able to tamper with my app, rebundle it, and run it without any issues. I need to prevent this. 

Dependencies
"expo": "^49.0.0",
"react-native": "0.72.10",
"freerasp-react-native": "^3.7.2",

**Comment by tompsota** [comment]
Hello @Mr-harsh10,

Did you get any report from the penetration tester? It would be awesome if you could share with us how the tester was able to bypass freeRASP - i.e. which tools were used, which part of freeRASP was bypassed, etc. 

You can also reach out to us at support@talsec.app - just please reference this issue.

Regards,
Tomas from Talsec

**Comment by Mr-harsh10** [comment]
Hello @tompsota thanks for the reply,
I don't know which tool was used by the testing team. But appIntegrity threat is detected on android but not on ios. 

 **which part of freeRASP was bypassed,** - **appIntegrity**
