### ISSUE TITLE
False Threat Warning of Unofficial store || Expo react native

### ISSUE THREAD

**Issue by Mr-harsh10** [talsec/Free-RASP-ReactNative#69]
In my expo react native project (production/release). I added supportedAlternativeStores: ['dev.firebase.appdistribution'] inside config to avoid threat warning of unofficialstore whenever I download app from firebase app distribution.

On downloading app from firebase app distribution I am getting threat warning of unofficialstore.

Config code
const config = {
    androidConfig: {
      packageName: "com.test.demo",
      certificateHashes: ["myhashhere="],
      supportedAlternativeStores: ['dev.firebase.appdistribution'],
    },
    iosConfig: {
      appBundleId: "com.test.demo",
      appTeamId: "myteamID",
    },
    watcherMail: "mysamplemailhere",
    isProd: true,
  };

General Information
"expo": "^49.0.0"
"react-native": "0.72.10",
"freerasp-react-native": "^3.8.0",

**Comment by tompsota** [comment]
Hello @Mr-harsh10,

The package name for Firebase App Distribution seems to be correct. 

Can you send us your Android package name and watcher mail to [support@talsec.app](mailto:support@talsec.app)? We'll look at the data and determine where is the problem. 

Thanks.

Tomas from Talsec

**Comment by deepanshuisky** [comment]
@tompsota Facing the same issue , can you please check
