### ISSUE TITLE
Build issue in android side

### ISSUE THREAD

**Issue by Gautham495** [talsec/Free-RASP-ReactNative#70]
**Describe the bug**
I am getting this build error while installing the app

* What went wrong:
Could not determine the dependencies of task ':freerasp-react-native:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':freerasp-react-native:debugCompileClasspath'.
   > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-ReactNative:9.6.0.
     Required by:
         project :freerasp-react-native
      > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-ReactNative:9.6.0.
         > Could not get resource 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/9.6.0/TalsecSecurity-Community-ReactNative-9.6.0.pom'.
            > Could not GET 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-ReactNative/9.6.0/TalsecSecurity-Community-ReactNative-9.6.0.pom'. Received status code 401 from server: Unauthorized

How to solve it?

**Comment by msikyna** [comment]
https://github.com/talsec/Free-RASP-Flutter/issues/118
