### ISSUE TITLE
How to restrict the user in login page for class component.

### ISSUE THREAD

**Issue by gkasireddy202** [talsec/Free-RASP-ReactNative#74]
How do you test the RSAP component in the class component?
Can we restrict the user login into the app?
example: Disable the login button on the login page.

**Comment by SirionRazzer** [comment]
Hi @gkasireddy202 ,
there is no way to do it, the freeRASP doesn't have a completion API. It's planned but we didn't implement it yet. Thank you for raising this up, seems a lot of people would appreciate that, we will consider escalating this request.
Best regards,
Tomas & Talsec team

**Comment by gkasireddy202** [comment]
@SirionRazzer - Thanks for your reply.
Can you please provide the example for class component?

**Comment by tompsota** [comment]
Hi @gkasireddy202,

Please take a look at this section of FAQ: https://github.com/talsec/Free-RASP-ReactNative?tab=readme-ov-file#alternative-initialize-freerasp-in-a-class-component

Regards,
Tomas from Talsec

**Comment by gkasireddy202** [comment]
@tompsota - Thanks for your reply.

I added the code to my index.js file from the below link. I ran the project on an ios device.
I did not see any console.log from this code. How to check the logs?
actions = {
    // Android & iOS
    privilegedAccess: () => {
      console.log('privilegedAccess');
    },
    // Android & iOS
    debug: () => {
      console.log('debug');
    },
    // Android & iOS
    simulator: () => {
      console.log('simulator');
      alert('simulator');
    },
    // Android & iOS
    appIntegrity: () => {
      console.log('appIntegrity');
    },
    // Android & iOS
    unofficialStore: () => {
      console.log('unofficialStore');
    },
    // Android & iOS
    hooks: () => {
      console.log('hooks');
    },
    // Android & iOS
    deviceBinding: () => {
      console.log('deviceBinding');
    },
    // Android & iOS
    secureHardwareNotAvailable: () => {
      console.log('secureHardwareNotAvailable');
    },
    // Android & iOS
    passcode: () => {
      console.log('passcode');
    },
    // iOS only
    deviceID: () => {
      console.log('deviceID');
    },
    // iOS only
    passcodeChange: () => {
      console.log('passcodeChange');
    },
  };
https://gist.github.com/tompsota/0ae2bb6a3d49d02dd7e8ea84da4c60cf

**Comment by tompsota** [comment]
Hi @gkasireddy202,

There was a bug in the gist, the setThreatListeners method has to be indeed awaited so it can receive callbacks from the SDK.
I updated the gist, if you try now, you should receive the callbacks.

Regards, 
Tomas from Talsec

**Comment by gkasireddy202** [comment]
@tompsota - Thanks for your reply.

**Comment by gkasireddy202** [comment]
There is no way to restrict the user without login into the app for class component.
Example: Disable the login button when the user has installed the app on the Root/Jailbreak device.

**Comment by tompsota** [comment]
Hi @gkasireddy202,

we suggest to initialize freeRASP in the entrypoint to your app, e.g. in App.js (or equivalent). Then, if you receive the privilegedAccess callback, you can disable the login button. If the user is already logged in, you can for example exit the app programatically, or log out the user, so he won't be able to continue using the app. 
Currently, freeRASP does not have ability to check whether the security audit is already completed if you would like to enable login only after that (it is coming in near future, so stay tuned!). Anyway, I won't recommend blocking app until freeRASP audit is completed, as it may slightly impact user experience.
Talsec offers also BusinessRASP, where you can configure reactions to threats directly in the SDK, so you won't need to configure anything in your code. See more info here: https://github.com/talsec/Free-RASP-ReactNative?tab=readme-ov-file#money_with_wings-talsec-commercial-subscriptions 

Best,
Tomas from Talsec

**Comment by gkasireddy202** [comment]
Hi @tompsota,

Thanks for your confirmation.
There is no way to restrict the user login into the app using the Free-RSAP component right?
We will receive only security reports from Talsec through email, right?

**Comment by tompsota** [comment]
Hi @gkasireddy202,

> There is no way to restrict the user login into the app using the Free-RSAP component right?
That's right. freeRASP provides just the callbacks, and you have to implement any restrictions yourself.

> We will receive only security reports from Talsec through email, right?
Right. However, we're currently working on improvements in this area as well, so you'll get even more insight into your data in the future.

Best,
Tomas from Talsec

**Comment by gkasireddy202** [comment]
@tompsota - Thanks for your update.
