### ISSUE TITLE
Unable to run on Android 14 device

### ISSUE THREAD

**Issue by gkasireddy202** [talsec/Free-RASP-ReactNative#75]
**Describe the bug**
Unable to run on Android device.

**To Reproduce**
Open the project after installing the package:npm install freerasp-react-native. My project does not run and shows the below error.
A problem occurred configuring project ':freerasp-react-native'.
> Could not resolve all artifacts for configuration ':freerasp-react-native:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0.
     Required by:
         project :freerasp-react-native
      > Cannot choose between the following variants of org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0:
          - gradle70JavadocElements
          - gradle70RuntimeElements
          - gradle70SourcesElements
          - javadocElements
          - runtimeElements
          - sourcesElements
        All of them match the consumer attributes:
          - Variant 'gradle70JavadocElements' capability org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0:
              - Unmatched attributes:
                  - Found org.gradle.category 'documentation' but wasn't required.
                  - Found org.gradle.docstype 'javadoc' but wasn't required.
                  - Required org.gradle.jvm.version '11' but no value provided.
                  - Required org.gradle.libraryelements 'jar' but no value provided.
                  - Found org.gradle.plugin.api-version '7.0' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'gradle70RuntimeElements' capability org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0:
              - Unmatched attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Found org.gradle.jvm.environment 'standard-jvm' but wasn't required.
                  - Found org.gradle.plugin.api-version '7.0' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'jvm' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.jvm.version '11' and found compatible value '8'.
                  - Required org.gradle.libraryelements 'jar' and found compatible value 'jar'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'gradle70SourcesElements' capability org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0:
              - Unmatched attributes:
                  - Found org.gradle.category 'documentation' but wasn't required.
                  - Found org.gradle.docstype 'sources' but wasn't required.
                  - Required org.gradle.jvm.version '11' but no value provided.
                  - Required org.gradle.libraryelements 'jar' but no value provided.
                  - Found org.gradle.plugin.api-version '7.0' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'javadocElements' capability org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0:
              - Unmatched attributes:
                  - Found org.gradle.category 'documentation' but wasn't required.
                  - Found org.gradle.docstype 'javadoc' but wasn't required.
                  - Required org.gradle.jvm.version '11' but no value provided.
                  - Required org.gradle.libraryelements 'jar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'runtimeElements' capability org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0:
              - Unmatched attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Found org.gradle.jvm.environment 'standard-jvm' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'jvm' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.jvm.version '11' and found compatible value '8'.
                  - Required org.gradle.libraryelements 'jar' and found compatible value 'jar'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'sourcesElements' capability org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0:
              - Unmatched attributes:
                  - Found org.gradle.category 'documentation' but wasn't required.
                  - Found org.gradle.docstype 'sources' but wasn't required.
                  - Required org.gradle.jvm.version '11' but no value provided.
                  - Required org.gradle.libraryelements 'jar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.

* Try:

**Expected behavior**
Run the app on an Android device

**Screenshots**
<img width="1362" alt="Screenshot 2024-07-29 at 4 20 32 PM" src="https://github.com/user-attachments/assets/ea03a0bb-5fde-41d0-886f-5b4ee5c1e683">

**Please complete the following information:**
 - Device: [e.g. Pixel 8]
 - OS version: [e.g. Android 14]
 - Version of freeRASP: [e.g. 3.8.1]
 - react-native:0.67.8
 - java version: 11.0.22

**Additional context**

**Comment by gkasireddy202** [comment]
Hi Team,

Please look at the issue. I facing this issue on Android only not on iOS.

**Comment by PaulHedrich** [comment]
Hi Talsec Team,
Is our error submission and request for assistance appropriate in this repository, or is there a more appropriate support request site? Thank you.

**Comment by msikyna** [comment]
Hello @gkasireddy202 , @PaulHedrich ,

we will look at the issue and get back to you soon. Thank you for reporting it!

Kind regards,
Talsec team

**Comment by tompsota** [comment]
Hello @gkasireddy202, @PaulHedrich,

It seems like Android Studio is using some version of Kotlin that is not compatible with 1.7.0, which is the default for freerasp.
You can modify the version of Kotlin for freerasp in top-level build.gradle file in buildscript.ext section. 
Try to set "kotlinVersion" property to the version you use in Android Studio. 

Let us know if it helped.

Best,
Tomas from Talsec

**Comment by gkasireddy202** [comment]
@tompsota - Thanks for your reply.
Can I set kotlinVersion property in my project level(MyProject>android>build.gradle) or node_modules>freersap-react-native>android>build.gradle?

If I add kotlinVersion in the project level could it affect other react-native components in my project?

**Comment by gkasireddy202** [comment]
@tompsota - I installed the freerasp-react-native component in react-native:0.73.7.
I am trying to generate the apk in release mode and getting the below errors.

> Task :freerasp-react-native:minifyReleaseWithR8 FAILED
AGPBI: {"kind":"error","text":"com.android.tools.r8.internal.Ub: Sealed classes are not supported as program classes when generating class files","sources":[{"file":"/MyProject/node_modules/freerasp-react-native/android/build/tmp/kotlin-classes/release/com/freeraspreactnative/Threat.class"}],"tool":"R8"}

com.android.tools.r8.internal.Ub: Sealed classes are not supported as program classes when generating class files.

**Comment by tompsota** [comment]
Hi @gkasireddy202,

> Can I set kotlinVersion property in my project level(MyProject>android>build.gradle) or node_modules>freersap-react-native>android>build.gradle?

You can set it in project level, but that could affect also other packages. You would have to try and see if the project compiles successfully. 
It is also possible to change the kotlin version just for freerasp: 
- Inside _node_modules/freerasp-react-native/android/gradle.properties_, edit the `FreeraspReactNative_kotlinVersion` variable. However, I'm not sure if freerasp would compile with lower version of kotlin.

> com.android.tools.r8.internal.Ub: Sealed classes are not supported as program classes when generating class files.

This is unfortunately issue with AGP version used in react-native:0:73, see this part of troubleshooting for more info and fix:
https://github.com/talsec/Free-RASP-ReactNative?tab=readme-ov-file#execution-failed-for-task-freerasp-react-nativeminifyreleasewithr8

**Comment by gkasireddy202** [comment]
Hi @tompsota ,

I checked the Gradle version in my project:distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip
As in the Google tracker, we do not have maven in android>build.gradle.We recently targeted my project to targetSdkVersion = 34.

<img width="566" alt="Screenshot 2024-08-06 at 5 22 14 PM" src="https://github.com/user-attachments/assets/8cb8c42b-f572-4ddc-a1a2-2386ce11062c">

**Comment by tompsota** [comment]
Hi @gkasireddy202,

you can place following dependency into android/build.gradle like so:
```
buildscript {
    dependencies {
        classpath("com.android.tools:r8:8.3.37")
    }
}
```

![Screenshot 2024-08-06 at 15 32 37](https://github.com/user-attachments/assets/f0d07260-6f00-4863-87ea-c26ca90e9663)

After that, the project should compile in release build.

Or alternatively, place the code from the Google issue tracker into android/**settings.gradle**


Best,
Tomas from Talsec

**Comment by msikyna** [comment]
Hello @gkasireddy202,

did the proposed solution worked? Thank you!

Kind regards,
Talsec team

**Comment by gkasireddy202** [comment]
@msikyna -  Yes. It is working fine now.
