### ISSUE TITLE
App Crash on launch when we set flag isProd to true

### ISSUE THREAD

**Issue by echonikul** [talsec/Free-RASP-ReactNative#90]
While upgrading the project from 0.68.7 to 0.72.0 . When I upload an app to the Play Store and change the flag isProd to true, it crash on launch

To Reproduce Steps to reproduce the behaviour:

Upgrade React Native project from version 0.68.7 to 0.72.0.
Configure freeRASP in the project.
Set the isProd flag to true.
Upload the app to the Play Store.
Launch the app after downloading.

Expected behaviour 
The app should launch successfully without crashing when isProd is set to true and after being uploaded to the Play Store.
   
 Device: All Android Devices
 OS : Android 
 Version of freeRASP:  ^3.9.1

Additional context: The issue only occurs when isProd is set to true. When the flag is set to false, the app runs without any issues. We are using the freeRASP (^3.9.1) package in React Native, and this behaviour began after upgrading from React Native 0.68.7 to 0.72.0.

**Comment by msikyna** [comment]
Hello @echonikul ,
could you please send us your watcherMail and package name to support@talsec.app? We will look at the data what incident is triggered (most likely appIntegrity).

Kind regards,
Talsec team

**Comment by echonikul** [comment]
Hi Matúš and the Talsec Team,

Thank you for the quick response.

Here are the requested details:

  *   WatcherMail: ***@***.******@***.***>
  *   Package Name: com.healthe.app


Please let me know if you need any further information to investigate the issue.

Looking forward to your assistance.

Kind regards,
Nikul Solanki

From: Matúš Šikyňa ***@***.***>
Date: Tuesday, 15 October 2024 at 12:25 PM
To: talsec/Free-RASP-ReactNative ***@***.***>
Cc: Nikul Solanki ***@***.***>, Mention ***@***.***>
Subject: Re: [talsec/Free-RASP-ReactNative] App Crash on launch when we set flag isProd to true (Issue #90)

Hello @echonikul<https://github.com/echonikul> ,
could you please send us your watcherMail and package name to ***@***.******@***.***>? We will look at the data what incident is triggered (most likely appIntegrity).

Kind regards,
Talsec team

**Comment by tompsota** [comment]
Hi @echonikul,

did you update also freeRASP in the process? We are aware of a bug in the latest freeRASP (3.9.1) that causes unresponsiveness in specific scenarios. I'm afraid your issue might be linked to this, actually. We'll be releasing fix in the upcoming days, but for now, can you try to use freeRASP@3.8.2? I think this should resolve the issue.

Best,
Tomas from Talsec

**Comment by echonikul** [comment]
Thank you for your response

I will check and let you know .

**Comment by tompsota** [comment]
Hi @echonikul,

we enhanced resilience against reverse engineering in 3.9.0, which caused issues on slower devices without access to the internet. This feature is not present in previous versions, so the issue is somewhere else.

Do you see any error messages in the console? If so, can you share them?

**Comment by echonikul** [comment]
i changed the build variant to release in android studio and check the issue in LogCat. 

i get this issue  

Error => com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 323 could not be found.

Version: 3.8.2

**Comment by echonikul** [comment]
Yes . Correct

**Comment by tompsota** [comment]
Allright. Does the project build, or is it runtime issue?

**Comment by echonikul** [comment]
Runtime issue . it crash when app opens

**Comment by tompsota** [comment]
Hi @echonikul,

I was not able to reproduce the issue locally. The com.facebook.react.uimanager.IllegalViewOperationException is not coming from our package; can you verify that the issue is caused by freeRASP? Or do you have any evidence pointing to it? 

The isProd flag does not have effect on which checks are executed, it just "hides" some of the failed checks so that you are not overwhelmed by many reports during development of the app. Therefore, freeRASP should not cause crashes only with isProd set to true - I can see just some issues with proguard rules in release build, but this would lead to build errors, which does not seem to be your case.

Best,
Tomas from Talsec

**Comment by echonikul** [comment]
If I comment out the freeRASP code, the app works fine. It also works when isProd is set to false.

**Comment by tompsota** [comment]
What are your reactions to callbacks? Is there any that should kill the app?

**Comment by echonikul** [comment]
@tompsota 

const actions = {
  privilegedAccess: () => RNExitApp.exitApp(),
  debug: () => RNExitApp.exitApp(),
  simulator: () => RNExitApp.exitApp(),
  appIntegrity: () => RNExitApp.exitApp(),
  unofficialStore: () => RNExitApp.exitApp(),
  hooks: () => RNExitApp.exitApp(),
  deviceBinding: () => RNExitApp.exitApp(),
  secureHardwareNotAvailable: () => RNExitApp.exitApp(),
  passcode: () => RNExitApp.exitApp(),
  deviceID: () => RNExitApp.exitApp(),
  obfuscationIssues: () => RNExitApp.exitApp(),
};

const config = {
  androidConfig: {
    packageName: "********",
    certificateHashes: ["********"],
  },
  iosConfig: {
    appBundleId: "******",
    appTeamId: "********",
  },
  watcherMail: "*****@gmail.com",
  isProd: true,
};

setThreatListeners(actions);
talsecStart(config);


Instead of using the useFreeRASP hook, we are using:

setThreatListeners(actions);
talsecStart(config);

in the release variant, and it’s working fine.

Is this okay?

**Comment by tompsota** [comment]
Hi @echonikul,

This is allright. The useFreerasp hook is there just for convenience, it contains just some some extra validation compared to these two methods.

Where in your code did you call the hook? It cannot be placed inside useEffect..

Regards,
Tomas from Talsec
