### ISSUE TITLE
Increased ANRs after 3.8.0+

### ISSUE THREAD

**Issue by MamoshiSE** [talsec/Free-RASP-ReactNative#92]
**Describe the bug**
After moving to freerasp-react-native 3.8+ where we started using useFreeRasp hook all our apps has had a huge increase of ANRs in production. With the main thread being blocked, haven't been able to find the issue. Our code is not inside a useEffect either. 

![ANR_TALSEC](https://github.com/user-attachments/assets/c316a482-7a73-4748-9368-388fadb621c5)

**To Reproduce**
  const actions = {
    // Android & iOS
    'privilegedAccess': () => {
    setFakeDevice(true);
    },
    // Android & iOS
    'debug': () => {
     setFakeDevice(true);
    },
    // Android & iOS
    'simulator': () => {
    setFakeDevice(true);
    },
    'systemVPN': () => {
      setVpn(true)
    },
  };

  useFreeRasp(config, actions);

**Comment by msikyna** [comment]
Hi @MamoshiSE ,
could you try the latest version? https://github.com/talsec/Free-RASP-ReactNative/releases/tag/v3.9.2
We fixed the ANR issue in 3.9.2.

Kind regards,
Talsec team

**Comment by echonikul** [comment]
Same issue here

**Comment by msikyna** [comment]
Hello @echonikul ,
could you also try with the new version? 3.9.2 or 3.9.3. Thank you!

**Comment by echonikul** [comment]
@msikyna  Okay bro

**Comment by tompsota** [comment]
Hi @MamoshiSE, @echonikul ,

Issue should be resolved in [v3.9.2](https://github.com/talsec/Free-RASP-ReactNative/releases/tag/v3.9.2). If the problem persists, feel free to reopen this.
