### ISSUE TITLE
New Architecture Support

### ISSUE THREAD

**Issue by Muhammad-Ahmad8** [talsec/Free-RASP-ReactNative#94]
Hi,
 Are there any plans to support new architecture?

**Comment by msikyna** [comment]
Hello @Muhammad-Ahmad8 ,
it is in our roadmap for the next year. We are currently working on enhancing our security features and implementing new features like screen recording detection.

Kind regards,
Talsec team

**Comment by tompsota** [comment]
Hello @Muhammad-Ahmad8,

We are currently researching support for the new architecture to ensure compatibility with the new versions of RN. We still have to test whether at least the interop layer is supported, but will try to resolve this quickly and will update you on progress.

Best,
Talsec team

**Comment by tompsota** [comment]
Hi @Muhammad-Ahmad8,
I tested the freeRASP plugin with New Architecture enabled and everything seems to be working as expected on both Android and iOS. 
Did you run into any issues during integration?

Regards,
Tomas from Talsec
